export const GET_ALL_BRANDS_REQUEST = "GET_ALL_BRANDS_REQUEST";
export const GET_ALL_BRANDS_REQUEST_SUCCESS = "GET_ALL_BRANDS_REQUEST_SUCCESS";
export const GET_ALL_BRANDS_REQUEST_FAIL = "GET_ALL_BRANDS_REQUEST_FAIL";

export const CREATE_BRAND_REQUEST = "CREATE_BRAND_REQUEST";
export const CREATE_BRAND_REQUEST_SUCCESS = "CREATE_BRAND_REQUEST_SUCCESS";
export const CREATE_BRAND_REQUEST_FAIL = "CREATE_BRAND_REQUEST_FAIL";

export const DELETE_BRAND_REQUEST = "DELETE_BRAND_REQUEST";
export const DELETE_BRAND_REQUEST_SUCCESS = "DELETE_BRAND_REQUEST_SUCCESS";
export const DELETE_BRAND_REQUEST_FAIL = "DELETE_BRAND_REQUEST_FAIL";

export const UPDATE_BRAND_REQUEST = "UPDATE_BRAND_REQUEST";
export const UPDATE_BRAND_REQUEST_SUCCESS = "UPDATE_BRAND_REQUEST_SUCCESS";
export const UPDATE_BRAND_REQUEST_FAIL = "UPDATE_BRAND_REQUEST_FAIL";
