export const GET_ALL_MODEL_REQUEST = "GET_ALL_MODEL_REQUEST";
export const GET_ALL_MODEL_REQUEST_SUCCESS = "GET_ALL_MODEL_REQUEST_SUCCESS";
export const GET_ALL_MODEL_REQUEST_FAIL = "GET_ALL_MODEL_REQUEST_FAIL";

export const CREATE_MODEL_REQUEST = "CREATE_MODEL_REQUEST";
export const CREATE_MODEL_REQUEST_SUCCESS = "CREATE_MODEL_REQUEST_SUCCESS";
export const CREATE_MODEL_REQUEST_FAIL = "CREATE_MODEL_REQUEST_FAIL";

export const DELETE_MODEL_REQUEST = "DELETE_MODEL_REQUEST";
export const DELETE_MODEL_REQUEST_SUCCESS = "DELETE_MODEL_REQUEST_SUCCESS";
export const DELETE_MODEL_REQUEST_FAIL = "DELETE_MODEL_REQUEST_FAIL";

export const UPDATE_MODEL_REQUEST = "UPDATE_MODEL_REQUEST";
export const UPDATE_MODEL_REQUEST_SUCCESS = "UPDATE_MODEL_REQUEST_SUCCESS";
export const UPDATE_MODEL_REQUEST_FAIL = "UPDATE_MODEL_REQUEST_FAIL";

export const GET_MODEL_BY_ID_REQUEST = "GET_MODEL_BY_ID_REQUEST";
export const GET_MODEL_BY_ID_REQUEST_SUCCESS =
  "GET_MODEL_BY_ID_REQUEST_SUCCESS";
export const GET_MODEL_BY_ID_REQUEST_FAIL = "GET_MODEL_BY_ID_REQUEST_FAIL";
