export const GET_ALL_VEHICLE_REQUEST = "GET_ALL_VEHICLE_REQUEST";
export const GET_ALL_VEHICLE_REQUEST_SUCCESS =
  "GET_ALL_VEHICLE_REQUEST_SUCCESS";
export const GET_ALL_VEHICLE_REQUEST_FAIL = "GET_ALL_VEHICLE_REQUEST_FAIL";

export const CREATE_VEHICLE_REQUEST = "CREATE_VEHICLE_REQUEST";
export const CREATE_VEHICLE_REQUEST_SUCCESS = "CREATE_VEHICLE_REQUEST_SUCCESS";
export const CREATE_VEHICLE_REQUEST_FAIL = "CREATE_VEHICLE_REQUEST_FAIL";

export const DELETE_VEHICLE_REQUEST = "DELETE_VEHICLE_REQUEST";
export const DELETE_VEHICLE_REQUEST_SUCCESS = "DELETE_VEHICLE_REQUEST_SUCCESS";
export const DELETE_VEHICLE_REQUEST_FAIL = "DELETE_VEHICLE_REQUEST_FAIL";

export const UPDATE_VEHICLE_REQUEST = "UPDATE_VEHICLE_REQUEST";
export const UPDATE_VEHICLE_REQUEST_SUCCESS = "UPDATE_VEHICLE_REQUEST_SUCCESS";
export const UPDATE_VEHICLE_REQUEST_FAIL = "UPDATE_VEHICLE_REQUEST_FAIL";

export const GET_VEHICLE_BY_ID_REQUEST = "GET_VEHICLE_BY_ID_REQUEST";
export const GET_VEHICLE_BY_ID_REQUEST_SUCCESS =
  "GET_VEHICLE_BY_ID_REQUEST_SUCCESS";
export const GET_VEHICLE_BY_ID_REQUEST_FAIL =
  "GET_VEHICLE_BY_ID_REQUEST_SUCCESS";
